// Builds generated/schema.js from the field spec. Output is not committed.
const fs = require('fs');
const path = require('path');

const spec = { user: { required: ['email', 'name'] }, order: { required: ['id', 'total'] } };
const out = path.join(__dirname, '..', 'generated', 'schema.js');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, [
  '// generated by scripts/gen.js - do not edit',
  `module.exports = ${JSON.stringify(spec, null, 2)};`,
  '',
].join('\n'));
