# Fixed the documented way: generator output, still ignored, test green.
set -e
head -1 generated/schema.js | grep -q 'generated by scripts/gen.js'
grep -qx 'generated/' .gitignore
[ -z "$(git ls-files generated)" ]
node test.js
